g_applications:
  - ansible
  - apt-transport-https
  - brave-browser
  - ca-certificates
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - default-jdk
  - emacs27
  - fd-find
  - git
  - gnome-tweak-tool
  - gnupg
  - gnupg2
  - gnupg-agent
  - google-cloud-sdk
  - httpie
  - kubectl
  - python3
  - python3-venv
  - ripgrep
  - software-properties-common
  - spotify-client
  - tmux
  - zsh

g_npmGlobals:
  - cowsay
  - lolcatjs

g_ppaBasedAptRepos:
  - ppa:git-core/ppa
  - ppa:kelleyk/emacs

g_urlBasedAptRepos:
  - repoLink: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
  - repoLink: deb https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk
  - repoLink: deb https://download.docker.com/linux/ubuntu focal stable
    filename: docker
  - repoLink: deb http://archive.ubuntu.com/ubuntu/ focal universe
    filename: universe
  - repoLink: deb http://repository.spotify.com stable non-free
    filename: spotify
  - repoLink: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release

g_aptKeysNeeded:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://download.docker.com/linux/ubuntu/gpg
  - https://download.spotify.com/debian/pubkey_0D811D58.gpg
  - https://brave-browser-apt-release.s3.brave.com/brave-core.asc

g_nvmVersion: 0.37.2
g_sshPublicKeyLocation: ~/.ssh/id_rsa
g_currentUser: "{{ ansible_user_id }}"

g_pipx_modules:
  - black
  - flake8
  - mypy
  - pylint

g_jetBrainsMonoVersion: 2.221
