g_applications:
  - ansible
  - apt-transport-https
  - audacity
  - brave-browser
  - build-essential
  - blueman
  - ca-certificates
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - default-jdk
  - entr
  - file
  - fd-find
  - git
  - gnome-tweak-tool
  - gnupg
  - gnupg2
  - gnupg-agent
  - google-cloud-sdk
  - google-chrome-stable
  - graphviz
  - guvcview
  - heroku
  - httpie
  - kubectl
  - libpq-dev
  - pavucontrol
  - postgresql
  - python3
  - python3.9
  - python3.9-dev
  - python3-venv
  - ripgrep
  - software-properties-common
  - spotify-client
  - tmux
  - terraform
  - virtualbox
  - v4l-utils
  - zsh

g_externalDebs:
  - https://zoom.us/client/latest/zoom_amd64.deb
  - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.19.2-amd64.deb

g_snapApplications:
  - discord
  - obs-studio
  - postman
  - vlc

g_flatpakApplications:
  - com.discordapp.Discord
  - com.obsproject.Studio
  - com.getpostman.Postman
  - org.videolan.VLC

g_flatpakRepos:
  - name: flathub
    url: https://dl.flathub.org/repo/flathub.flatpakrepo

g_homebrewApplications:
  - aws-vault
  - act
   
g_npmGlobals:
  - c4builder
  - cowsay
  - lolcatjs
  - npm-check-updates
  - serverless
  - yarn

g_ppaBasedAptRepos:
  - ppa:git-core/ppa
  - ppa:ubuntuhandbook1/audacity

g_urlBasedAptRepos:
  - repoLink: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
  - repoLink: deb https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk
  - repoLink: deb https://download.docker.com/linux/ubuntu focal stable
    filename: docker
  - repoLink: deb http://archive.ubuntu.com/ubuntu/ focal universe
    filename: universe
  - repoLink: deb http://archive.ubuntu.com/ubuntu/ focal multiverse
    filename: multiverse
  - repoLink: deb http://repository.spotify.com stable non-free
    filename: spotify
  - repoLink: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release
  - repoLink: deb https://cli-assets.heroku.com/apt ./
    filename: heroku
  - repoLink: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
    filename: pgdg
  - repoLink: deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/ focal main
    filename: deadsnakes
  - repoLink: deb http://cz.archive.ubuntu.com/ubuntu focal main
    filename: python-dependencies
  - repoLink: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    filename: terraform

g_aptKeysNeeded:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://download.docker.com/linux/ubuntu/gpg
  - https://download.spotify.com/debian/pubkey_0D811D58.gpg
  - https://brave-browser-apt-release.s3.brave.com/brave-core.asc
  - https://cli-assets.heroku.com/apt/release.key
  - https://www.postgresql.org/media/keys/ACCC4CF8.asc
  - https://apt.releases.hashicorp.com/gpg

g_appImages:
  - url: https://github.com/bitwarden/desktop/releases/download/v1.24.6/Bitwarden-1.24.6-x86_64.AppImage
    destName: Bitwarden-1.24.6-x86_64

g_nvmVersion: 0.37.2
g_sshPublicKeyLocation: ~/.ssh/id_rsa
g_currentUser: "{{ ansible_user_id }}"

g_pipx_modules:
  - black
  - flake8
  - isort
  - mypy
  - pylint
  - pytest
  - virtualenv

g_homebrewVersion: 2.7.5
