g_applications:
  - ansible
  - apt-transport-https
  - ca-certificates
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - default-jdk
  - emacs27
  - fd-find
  - git
  - gnome-tweak-tool
  - gnupg
  - gnupg2
  - gnupg-agent
  - google-cloud-sdk
  - httpie
  - kubectl
  - python3
  - python3-venv
  - ripgrep
  - software-properties-common
  - tmux
  - zsh

g_npmGlobals:
  - cowsay
  - lolcatjs

g_ppaBasedAptRepos:
  - ppa:git-core/ppa
  - ppa:kelleyk/emacs

g_urlBasedAptRepos:
  - repoLink: deb https://apt.kubernetes.io/ kubernetes-focal main
    filename: kubernetes
  - repoLink: deb https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk
  - repoLink: deb https://download.docker.com/linux/ubuntu focal stable
    filename: docker
  - repoLink: deb http://archive.ubuntu.com/ubuntu/ focal universe
    filename: universe

g_aptKeysNeeded:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://download.docker.com/linux/ubuntu/gpg

g_nvmVersion: 0.37.2
g_sshPublicKeyLocation: ~/.ssh/id_rsa
g_currentUser: "{{ ansible_user_id }}"

g_pipx_modules:
  - black
  - flake8
  - pylint
  - mypy

g_jetBrainsMonoVersion: 2.221
