g_applications:
  - ansible
  - apt-transport-https
  - default-jdk
  - git
  - gnupg2
  - httpie
  - kubectl
  - software-properties-common
  - tmux
  - zsh

g_npmGlobals:
  - cowsay
  - lolcatjs

g_ppaBasedAptRepos:
  - ppa:git-core/ppa

g_urlBasedAptRepos:
  - repoLink: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

g_nvmVersion: 0.37.2
g_sshPublicKeyLocation: ~/.ssh/id_rsa
g_currentUser: "{{ ansible_user_id }}"
