vars_prompt:
  - name: github_ssh_auth_token
    prompt: "If you haven't already uploaded your github ssh key then I need your personal access token to upload it"

vars:
  applications:
    - ansible
    - apt-transport-https
    - git
    - gnupg2
    - httpie
    - kubectl
    - software-properties-common
    - zsh

  npmGlobals:
    - cowsay
    - lolcatjs

  ppaBasedAptRepos:
    - ppa:git-core/ppa

  urlBasedAptRepos:
    - repoLink: deb https://apt.kubernetes.io/ kubernetes-xenial main
      filename: kubernetes

  nvmVersion: 0.37.2
  sshPublicKeyLocation: ~/.ssh/id_rsa
  currentUser: "{{ ansible_user_id }}"
