g_applications:
  - ansible
  - apt-transport-https
  - audacity
  - brave-browser
  - build-essential
  - ca-certificates
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - default-jdk
  - emacs27
  - file
  - fd-find
  - git
  - git-lfs=2.13.2
  - gnome-tweak-tool
  - gnupg
  - gnupg2
  - gnupg-agent
  - google-cloud-sdk
  - guvcview
  - httpie
  - kubectl
  - python3
  - python3-venv
  - ripgrep
  - software-properties-common
  - spotify-client
  - tmux
  - virtualbox
  - zsh

g_externalDebs:
  - https://zoom.us/client/latest/zoom_amd64.deb
  - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.12.1-amd64.deb
  - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

g_snapApplications:
  - discord
  - obs-studio
  - postman
  - vlc

g_homebrewApplications:
  - aws-vault
   
g_npmGlobals:
  - c4builder
  - cowsay
  - lolcatjs
  - yarn

g_ppaBasedAptRepos:
  - ppa:git-core/ppa
  - ppa:kelleyk/emacs
  - ppa:ubuntuhandbook1/audacity

g_urlBasedAptRepos:
  - repoLink: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
  - repoLink: deb https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk
  - repoLink: deb https://download.docker.com/linux/ubuntu focal stable
    filename: docker
  - repoLink: deb http://archive.ubuntu.com/ubuntu/ focal universe
    filename: universe
  - repoLink: deb http://archive.ubuntu.com/ubuntu/ focal multiverse
    filename: multiverse
  - repoLink: deb http://repository.spotify.com stable non-free
    filename: spotify
  - repoLink: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    filename: brave-browser-release
  - repoLink: deb https://packagecloud.io/github/git-lfs/ubuntu/ focal main
    filename: github_git-lfs

g_aptKeysNeeded:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://download.docker.com/linux/ubuntu/gpg
  - https://download.spotify.com/debian/pubkey_0D811D58.gpg
  - https://brave-browser-apt-release.s3.brave.com/brave-core.asc
  - https://packagecloud.io/github/git-lfs/gpgkey

g_nvmVersion: 0.37.2
g_sshPublicKeyLocation: ~/.ssh/id_rsa
g_currentUser: "{{ ansible_user_id }}"

g_pipx_modules:
  - black
  - flake8
  - mypy
  - pylint
  - pytest
  - virtualenv

g_jetBrainsMonoVersion: 2.221
g_homebrewVersion: 2.7.5
