g_applications:
  - ansible
  - apt-transport-https
  - ca-certificates
  - default-jdk
  - git
  - gnupg
  - gnupg2
  - google-cloud-sdk
  - httpie
  - kubectl
  - python3
  - software-properties-common
  - tmux
  - zsh

g_npmGlobals:
  - cowsay
  - lolcatjs

g_ppaBasedAptRepos:
  - ppa:git-core/ppa

g_urlBasedAptRepos:
  - repoLink: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes
  - repoLink: deb https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk

g_nvmVersion: 0.37.2
g_sshPublicKeyLocation: ~/.ssh/id_rsa
g_currentUser: "{{ ansible_user_id }}"

g_pipx_modules:
  - black
  - flake8
  - pylint
  - mypy
