- hosts: all
  vars_prompt:
    - name: github_ssh_auth_token
      prompt: "If you haven't already uploaded your github ssh key then I need your personal access token to upload it"
  vars_files:
    - main/defaults/main.yml
  tasks:
    - name: Make the temporary install directory
      file:
        path: ~/.inst_temp
        state: directory
        mode: '0755'

    - import_tasks: main/tasks/application-installs.yml
      vars:
        - applications: "{{ g_applications }}"
        - ppaBasedAptRepos: "{{ g_ppaBasedAptRepos }}"
        - urlBasedAptRepos: "{{ g_urlBasedAptRepos }}"
        - aptKeysNeeded: "{{ g_aptKeysNeeded }}"
        - externalDebs: "{{ g_externalDebs }}"
        - snapApplications: "{{ g_snapApplications }}"

    - import_tasks: main/tasks/git.yml
      vars:
        - sshPublicKeyLocation: "{{ g_sshPublicKeyLocation }}"

    - import_tasks: main/tasks/homebrew.yml
      vars:
        - homebrewVersion: "{{ g_homebrewVersion }}"
        - homebrewApplications: "{{ g_homebrewApplications }}"

    - import_tasks: main/tasks/nvm.yml
      vars:
        - nvmVersion: "{{ g_nvmVersion }}"

    - name: Pull down dotfiles
      git:
        repo: "git@github.com:zacbraddy/lolswagfiles9000.git"
        dest: ~/Projects/Personal/lolswagfiles9000

    - import_tasks: main/tasks/oh-my-zsh.yml
      vars:
        - currentUser: "{{ g_currentUser }}"

    - import_tasks: main/tasks/node.yml
      vars:
        - npmGlobals: "{{ g_npmGlobals }}"

    - import_tasks: main/tasks/kubectx.yml

    - import_tasks: main/tasks/tmux.yml

    - import_tasks: main/tasks/plant-uml.yml

    - import_tasks: main/tasks/python-and-friends.yml
      vars:
        pipx_modules: "{{ g_pipx_modules }}"

    - import_tasks: main/tasks/docker.yml

    - import_tasks: main/tasks/doom-emacs.yml
      vars:
        jetBrainsMonoVersion: "{{ g_jetBrainsMonoVersion }}"

    - import_tasks: main/tasks/os-settings.yml

    - import_tasks: main/tasks/aws.yml
      vars:
        - currentUser: "{{ g_currentUser }}"

    - name: Clean up install temp directory
      file:
        path: ~/.inst_temp
        state: absent
