- hosts: all
  vars_prompt:
    - name: github_ssh_auth_token
      prompt: "If you haven't already uploaded your github ssh key then I need your personal access token to upload it"
  vars_files:
    - main/defaults/main.yml
  tasks:
    - import_tasks: main/tasks/apt-installs.yml
      vars:
        - applications: "{{ g_applications }}"
        - ppaBasedAptRepos: "{{ g_ppaBasedAptRepos }}"
        - urlBasedAptRepos: "{{ g_urlBasedAptRepos }}"

    - import_tasks: main/tasks/configure-git.yml
      vars:
        - sshPublicKeyLocation: "{{ g_sshPublicKeyLocation }}"

    - import_tasks: main/tasks/install-nvm.yml
      vars:
        - nvmVersion: "{{ g_nvmVersion }}"

    - name: Pull down dotfiles
      git:
        repo: "git@github.com:zacbraddy/lolswagfiles9000.git"
        dest: ~/Projects/Personal/lolswagfiles9000

    - import_tasks: main/tasks/install-configure-omz.yml
      vars:
        - currentUser: "{{ g_currentUser }}"

    - import_tasks: main/tasks/install-node.yml
      vars:
        - npmGlobals: "{{ g_npmGlobals }}"

    - import_tasks: main/tasks/kubectx.yml
