- name: Confirm NVM install
  shell: "source ~/.zshrc && nvm --version"
  register: nvm_installed
  ignore_errors: true
  failed_when: False
  changed_when: nvm_installed.stdout != nvmVersion
  args:
    executable: /bin/zsh

- name: Get NVM install script
  uri:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvmVersion }}/install.sh
    method: GET
    return_content: yes
  register: nvm_install_script
  when: nvm_installed.stdout != nvmVersion

- name: Install NVM
  shell: "{{ nvm_install_script.content }}"
  when: nvm_installed.stdout != nvmVersion
  args:
    executable: /bin/bash
