- name: Load global vars
  include_vars:
    dir: ../defaults
    name: main.yml

- name: Ensure we have the gcloud apt-key
  become: yes
  become_method: sudo
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ aptKeysNeeded }}"

- name: Add necessary url based apt repos
  become: yes
  become_method: sudo
  apt_repository:
    repo: "{{ item.repoLink }}"
    state: present
    filename: "{{ item.filename }}"
  loop: "{{ urlBasedAptRepos }}"

- name: Add necessary ppa based apt repos
  become: yes
  become_method: sudo
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ ppaBasedAptRepos }}"

- name: Install Applications
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ applications }}"

- name: Install External Deb applications
  become: yes
  become_method: sudo
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ externalDebs }}"

- name: Install Snap packages
  become: yes
  become_method: sudo
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop: "{{ snapApplications }}"

- name: Download appImages
  get_url:
    url: "{{ appImages.url }}"
    dest: "~/appImages/{{ appImages.destName }}.AppImage"
    mode: '0755'
    force: no
