- name: Ensure we have AWS CLI
  shell: aws --version
  register: aws_installed
  changed_when: aws_installed.rc != 0
  failed_when: False
  args:
    executable: /bin/zsh

- name: Make sure we have the aws cli install directory
  command:
    cmd: "mkdir -p ~/.inst_temp/awscli"
    warn: false
  when: aws_installed.rc != 0

- name: Download AWS CLI installer
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "~/.inst_temp/awscli"
    remote_src: yes
  when: aws_installed.rc != 0

- name: Install AWS CLI
  become: yes
  become_method: sudo
  shell: "/home/{{ currentUser }}/.inst_temp/awscli/install"
  args:
    executable: /bin/zsh
  when: aws_installed.rc != 0
