- name: Ensure docker service has been started
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  become: yes
  become_method: sudo
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    force: no
  args:
    creates: /usr/local/bin/docker-compose
