- name: Pull down doom emacs git and put over the top of emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
    depth: "1"

- name: Make sure we have a doom emacs directory
  command:
    cmd: "mkdir -p ~/.doom.d"
    warn: false

- name: Setup symlinks for doom emacs
  file:
    src: "~/Projects/Personal/lolswagfiles9000/doom-emacs/{{ item }}"
    dest: "~/.doom.d/{{ item }}"
    force: true
    state: link
  with_items:
    - config.el
    - init.el
    - packages.el

- name: Generate doom emacs env file
  shell: "source ~/.zshrc && doom env"
  args:
    executable: "/bin/zsh"
     
- name: Install/Upgrade doom emacs
  shell: "source ~/.zshrc && (yes | doom -y install)"
  args:
    executable: "/bin/zsh"

- name: Make sure we have a fonts directory
  command:
    cmd: "mkdir -p ~/.local/share/fonts"
    warn: false

- name: Check if JetBrains Mono is installed
  shell: "ls -al ~/.local/share/fonts | grep -c JetBrains"
  register: jetbrains_mono_installed
  changed_when: jetbrains_mono_installed.rc != 0 or jetbrains_mono_installed.stdout != 2
  failed_when: False
  args:
    executable: /bin/zsh

- name: Make sure we have a fonts directory
  command:
    cmd: "mkdir -p ~/.inst_temp/JetBrainsMono-{{ jetBrainsMonoVersion }}"
    warn: false
  when: jetbrains_mono_installed.rc != 0 or jetbrains_mono_installed.stdout != 2

- name: Download JetBrains Mono fonts
  unarchive:
    src: "https://download.jetbrains.com/fonts/JetBrainsMono-{{ jetBrainsMonoVersion }}.zip"
    dest: "~/.inst_temp/JetBrainsMono-{{ jetBrainsMonoVersion }}"
    remote_src: yes
  when: jetbrains_mono_installed.rc != 0 or jetbrains_mono_installed.stdout != 2

- name: Place fonts in font folder
  shell: "mv ~/.inst_temp/JetBrainsMono-{{ jetBrainsMonoVersion }}/fonts/ttf/JetBrainsMono-Regular.ttf ~/.local/share/fonts/JetBrainsMono-{{ jetBrainsMonoVersion }}/fonts/ttf/JetBrainsMono-Regular.ttf && mv ~/.inst_temp/JetBrainsMono-{{ jetBrainsMonoVersion }}/fonts/ttf/JetBrainsMono-Italic.ttf ~/.local/share/fonts/JetBrainsMono-{{ jetBrainsMonoVersion }}/fonts/ttf/JetBrainsMono-Italic.ttf"
  when: jetbrains_mono_installed.rc != 0 or jetbrains_mono_installed.stdout != 2
  args:
    executable: /bin/zsh

- name: Refresh fonts cache
  shell: fc-cache -f
  when: jetbrains_mono_installed.rc != 0 or jetbrains_mono_installed.stdout != 2
  args:
    executable: /bin/zsh
