- name: Pull down doom emacs git and put over the top of emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
    depth: "1"

- name: Make sure we have a doom emacs directory
  command:
    cmd: "mkdir -p ~/.doom.d"
    warn: false

- name: Setup symlinks for doom emacs
  file:
    src: "~/Projects/Personal/lolswagfiles9000/doom-emacs/{{ item }}"
    dest: "~/.doom.d/{{ item }}"
    force: true
    state: link
  with_items:
    - config.el
    - init.el
    - packages.el

- name: Install/Upgrade doom emacs
  shell: "source ~/.zshrc && doom install"
  args:
    executable: "/bin/zsh"
