- name: Pull down doom emacs git and put over the top of emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
    depth: "1"

- name: Setup symlinks for OhMyZSH files
  file:
    src: "~/Projects/Personal/lolswagfiles9000/doom-emacs/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    force: true
    state: link
  with_items:
    - src: .zshrc
      dest: .zshrc

- name: Install/Upgrade doom emacs
  shell: "source ~/.zshrc && doom install"
  args:
    executable: "/bin/zsh"
