- name: Check for existing ssh keys
  stat:
    path: ~/.ssh/id_rsa.pub
  register: sshkeys_exist

- name: Generate SSH keys
  shell: "ssh-keygen -t rsa -N '' -f {{ sshPublicKeyLocation }} <<< y"
  when: not sshkeys_exist.stat.exists
  args:
    executable: /bin/bash

- name: Read SSH keys into memory
  command: cat ~/.ssh/id_rsa.pub
  register: sshPublicKey

- name: Upload SSH keys to Github
  uri:
    method: POST
    url: https://api.github.com/user/keys
    body_format: json
    status_code:
      - 201
      - 304
    body:
      key: "{{ sshPublicKey.stdout }}"
      title: "{{ ansible_hostname }}"
    headers:
      Accept: application/vnd.github.v3+json
      Authorization: "token {{ github_ssh_auth_token }}"
  when: github_ssh_auth_token|length != 0

- name: Ensure github is present in known_hosts file
  known_hosts:
    name: "github.com"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"

- name: Setup symlinks for gitconfig
  file:
    src: "~/Projects/Personal/lolswagfiles9000/{{ item }}"
    dest: "~/{{ item }}"
    force: true
    state: link
  with_items:
    - .gitconfig
    - .gitignore_global

- name: Get Git LFS install script
  uri:
    url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
    method: GET
    return_content: yes
  register: gitlfs_install_script

- name: Run git LFS install script
  shell: "{{ gitlfs_install_script.content }}"
  environment:
    - os: "ubuntu"
    - dist: "focal"
  args:
    executable: /bin/bash

- name: Install Git LFS into git
  shell: "git lfs install"
