- name: Confirm homebrew install
  shell: "source ~/.zshrc && brew --version"
  register: homebrew_installed
  ignore_errors: true
  failed_when: False
  changed_when: homebrew_installed.stdout != homebrewVersion
  args:
    executable: /bin/zsh

- name: Get Homebrew install script
  uri:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    method: GET
    return_content: yes
  register: homebrew_install_script
  when: homebrew_installed.stdout != homebrewVersion

- name: Install Homebrew
  shell: "{{ homebrew_install_script.content }}"
  when: homebrew_installed.stdout != homebrewVersion
  args:
    executable: /bin/bash

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrewApplications }}"
