- name: "Do we have jetbrains toolbox because force=no doesn't seem to work!!"
  stat:
    path: "~/jetbrains-toolbox"
  register: jetbrainsToolbox

- name: Download Jetbrains Toolbox
  unarchive:
    src: https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-1.20.7940.tar.gz
    dest: "~/jetbrains-toolbox"
    remote_src: yes
  when: not jetbrainsToolbox.stat.exists

- name: Setup symlinks for idea vim
  file:
    src: "~/Projects/Personal/lolswagfiles9000/.ideavimrc"
    dest: "~/.ideavimrc"
    force: true
    state: link
