- name: Check if we have kubectx
  shell: kb
  register: kubectx_installed
  ignore_errors: true
  changed_when: kubectx_installed.rc != 0
  failed_when: false
  args:
    executable: /bin/zsh

- name: Make the kubectx directory
  command:
    cmd: "mkdir -p ~/.kubectx"
    warn: false

- name: Get kubectx scripts
  get_url:
    url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/{{ item }}"
    dest: "~/.kubectx/{{ item }}"
    mode: '0755'
  with_items:
    - kubectx
    - kubens

- name: Get completions for ZSH
  get_url:
    url: "https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/_{{ item }}.zsh"
    dest: "~/.oh-my-zsh/completions/_{{ item }}.zsh"
    mode: '0755'
  with_items:
    - kubectx
    - kubens
