- name: Install psutil so we can do gnome tweaks
  shell: "source ~/.zshrc && pip3 install psutil"
  args:
    executable: /bin/zsh

- name: Nobody likes looking at docks all the time now do they?
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"
    state: present
     
- name: Make UK keyboard the only keyboard input layout
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'gb')]"
    state: present

- name: Maybe redundant but make sure that the Jolly ol GB keyboard is selected as the keyboard to us
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/current"
    value: "0"
    state: present

- name: Set desktop settings to be dark as the night
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
    state: present

- name: Mouse cursor gotta be white
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'DMZ-White'"
    state: present

- name: Icons wanna be dark
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'ubuntu-mono-dark'"
    state: present

- name: Put in my keyboard tweaks
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:backspace', 'shift:both_capslock']"
    state: present

- name: And all my favourite apps will be there
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['slack.desktop', 'spotify.desktop', 'brave-browser.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'gnome-control-center.desktop', 'org.gnome.Characters.desktop', 'postman_postman.desktop', 'discord_discord.desktop', 'snap-store_ubuntu-software.desktop']"
    state: present

- name: Setup symlinks for default applications
  file:
    src: "~/Projects/Personal/lolswagfiles9000/mimeapps.list"
    dest: "~/.config/mimeapps.list"
    force: true
    state: link
