- name: Install psutil so we can do gnome tweaks
  shell: "source ~/.zshrc && pip3 install psutil"
  args:
    executable: /bin/zsh

- name: Make UK keyboard the only keyboard input layout
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'gb')]"
    state: present

- name: Maybe redundant but make sure that the Jolly ol GB keyboard is selected as the keyboard to us
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/current"
    value: "0"
    state: present

- name: Set desktop settings to be dark as the night
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
    state: present

- name: Mouse cursor gotta be white
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'DMZ-White'"
    state: present

- name: Icons wanna be dark
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'ubuntu-mono-dark'"
    state: present

- name: Put in my keyboard tweaks
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:backspace', 'shift:both_capslock']"
    state: present

- name: Is GB locale in the house?
  locale_gen:
    name: en_GB.UTF-8
    state: present

- name: I'm in GB ya'll so set it that way
  command: localectl set-locale LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8

- name: Also I like my dates all GB-y
  community.general.dconf:
    key: "/system/locale/region"
    value: "'en_GB.UTF-8'"
    state: present
