- name: "Do we already have plantuml, because force=no doesn't seem to work!!"
  stat:
    path: ~/plantuml.jar
  register: plantuml

- name: Download PlantUML jar
  get_url:
    url: https://sourceforge.net/projects/plantuml/files/plantuml.jar
    dest: ~/plantuml.jar
    force: no
  when: not plantuml.stat.exists
