- name: Ensure we actually have pip itself, crazy but it happens!
  shell: python3 -m pip --version
  register: pip_installed
  changed_when: pip_installed.rc != 0
  failed_when: False
  args:
    executable: /bin/zsh

- name: Get the pip install script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: ~/.inst_temp/get-pip.py
  when: pip_installed.rc != 0

- name: Install pip
  shell: "python3 ~/.inst_temp/get-pip.py"
  when: pip_installed.rc != 0
  args:
    executable: /bin/zsh
   
- name: Install pipx
  shell: python3 -m pip install --user pipx
  args:
    executable: /bin/zsh

- name: Ensure that pipx is in the path variable
  shell: python3 -m pipx ensurepath
  args:
    executable: /bin/zsh

- name: Install pipx modules
  shell: "source ~/.zshrc && pipx install {{ item }}"
  loop: "{{ pipx_modules }}"
  args:
    executable: /bin/zsh

- name: Ensure we have poetry
  shell: poetry --version
  register: poetry_installed
  changed_when: poetry_installed.rc != 0
  failed_when: False
  args:
    executable: /bin/zsh

- name: Get the poetry install script
  get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
    dest: ~/.inst_temp/get-poetry.py
  when: poetry_installed.rc != 0

- name: Install poetry
  shell: "python3 ~/.inst_temp/get-poetry.py"
  when: poetry_installed.rc != 0
  args:
    executable: /bin/zsh
