- name: Ensure we have Terraform CLI
  shell: terraform --version
  register: terraform_installed
  changed_when: terraform_installed.rc != 0
  failed_when: False
  args:
    executable: /bin/zsh

- name: Download Terraform CLI
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
    dest: "~/.inst_temp/terraform"
    remote_src: yes
  when: terraform_installed.rc != 0

- name: Move terraform executable where it should be
  command:
    cmd: "mv ~/.inst_temp/terraform/terraform ~/terraform"