# Vibrant Dracula-themed Powerlevel10k configuration
# Maximum visual appeal with full color palette!

# Enable instant prompt (for fast startup)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Visual configuration - make it colorful!
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{#bd93f9}╭─%f '
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%F{#bd93f9}├─%f '
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{#bd93f9}╰─%f %F{#50fa7b}❯%f '

# Dracula color palette
typeset -g DRACULA_BACKGROUND='#282a36'
typeset -g DRACULA_CURRENT_LINE='#44475a'
typeset -g DRACULA_FOREGROUND='#f8f8f2'
typeset -g DRACULA_COMMENT='#6272a4'
typeset -g DRACULA_CYAN='#8be9fd'
typeset -g DRACULA_GREEN='#50fa7b'
typeset -g DRACULA_ORANGE='#ffb86c'
typeset -g DRACULA_PINK='#ff79c6'
typeset -g DRACULA_PURPLE='#bd93f9'
typeset -g DRACULA_RED='#ff5555'
typeset -g DRACULA_YELLOW='#f1fa8c'

# Left prompt elements - more colorful segments
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon               # colorful OS icon
  dir                   # current directory
  vcs                   # git status
  node_version         # node version if in node project
  python_version       # python version if in python project
  newline              # line break
)

# Right prompt elements - vibrant info
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                # exit code
  command_execution_time # command duration
  background_jobs       # background jobs
  load                  # system load
  ram                   # memory usage
  time                  # current time
)

# OS icon - bright and colorful
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$DRACULA_PURPLE
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_LINUX_ARCH_ICON='🐧'

# Directory - vibrant purple with nice styling
typeset -g POWERLEVEL9K_DIR_BACKGROUND=$DRACULA_CURRENT_LINE
typeset -g POWERLEVEL9K_DIR_FOREGROUND=$DRACULA_CYAN
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$DRACULA_COMMENT
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$DRACULA_PINK
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=''
typeset -g POWERLEVEL9K_DIR_PREFIX=' 📁 '
typeset -g POWERLEVEL9K_DIR_SUFFIX=' '

# Git VCS - full rainbow of git states
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$DRACULA_GREEN
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$DRACULA_ORANGE
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$DRACULA_YELLOW
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_VCS_STAGED_BACKGROUND=$DRACULA_CYAN
typeset -g POWERLEVEL9K_VCS_STAGED_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_BACKGROUND=$DRACULA_PURPLE
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_BACKGROUND=$DRACULA_PINK
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=$DRACULA_RED
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$DRACULA_FOREGROUND
typeset -g POWERLEVEL9K_VCS_PREFIX=' 🌿 '
typeset -g POWERLEVEL9K_VCS_SUFFIX=' '

# Node version - green themed
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=$DRACULA_GREEN
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_NODE_VERSION_PREFIX=' ⬢ '
typeset -g POWERLEVEL9K_NODE_VERSION_SUFFIX=' '

# Python version - yellow themed
typeset -g POWERLEVEL9K_PYTHON_VERSION_BACKGROUND=$DRACULA_YELLOW
typeset -g POWERLEVEL9K_PYTHON_VERSION_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_PYTHON_VERSION_PREFIX=' 🐍 '
typeset -g POWERLEVEL9K_PYTHON_VERSION_SUFFIX=' '

# Status - bright red for errors
typeset -g POWERLEVEL9K_STATUS_VERBOSE=true
typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=$DRACULA_GREEN
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_STATUS_OK_PREFIX=' ✔ '
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=$DRACULA_RED
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$DRACULA_FOREGROUND
typeset -g POWERLEVEL9K_STATUS_ERROR_PREFIX=' ✘ '

# Command execution time - orange theme
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=$DRACULA_ORANGE
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX=' ⏱ '
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_SUFFIX=' '

# Background jobs - purple theme
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=$DRACULA_PURPLE
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_PREFIX=' ⚙ '

# System load - pink theme
typeset -g POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND=$DRACULA_RED
typeset -g POWERLEVEL9K_LOAD_WARNING_BACKGROUND=$DRACULA_ORANGE
typeset -g POWERLEVEL9K_LOAD_NORMAL_BACKGROUND=$DRACULA_PINK
typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=$DRACULA_FOREGROUND
typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_LOAD_PREFIX=' 💻 '

# RAM usage - cyan theme
typeset -g POWERLEVEL9K_RAM_BACKGROUND=$DRACULA_CYAN
typeset -g POWERLEVEL9K_RAM_FOREGROUND=$DRACULA_BACKGROUND
typeset -g POWERLEVEL9K_RAM_PREFIX=' 🧠 '

# Time - comment color with nice styling
typeset -g POWERLEVEL9K_TIME_BACKGROUND=$DRACULA_COMMENT
typeset -g POWERLEVEL9K_TIME_FOREGROUND=$DRACULA_FOREGROUND
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_PREFIX=' 🕐 '

# Enhanced prompt gap styling
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND='none'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=$DRACULA_COMMENT

# Segment separators - make transitions smooth
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' | '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' | '

# Transient prompt
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=same-dir

# Performance settings
typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=4096
typeset -g POWERLEVEL9K_VCS_STAGED_MAX_NUM=10
typeset -g POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=10
typeset -g POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM=10

# Enhanced icons
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON='󰘎 '
typeset -g POWERLEVEL9K_VCS_COMMIT_ICON=' '
typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'

# Clean spacing
typeset -g POWERLEVEL9K_LEGACY_ICON_SPACING=false
typeset -g ZLE_RPROMPT_INDENT=0

# Apply configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
